### ISSUE TITLE
Installing Anemone respring still loading

### ISSUE THREAD

**Issue by tercelazul** [AnemoneTeam/Anemone-OSS#10]
I only install anemone from cydia, but when i press the respring buttom after install it turn me to an a minute loading logo and then RESTART the phone. The i need to Jailbreak again because the RESTART. I think it's the pincrush dependence because when i install the package stock a little waiting in the pincrush dependence.

Device: iPhone 8
iOS: 11.1.2

**Comment by PATLERNG15** [comment]
app good

**Comment by khuongduy1110** [comment]
Good

**Comment by RealPortalPlayer** [comment]
Thats iOS 11... this supports up to iOS 10
